name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: self-hosted
    env:
      PORT: 5001
      MONGODB_ADMIN_URI: ${{ secrets.MONGODB_ADMIN_URI }}
      MONGODB_PUBLIC_URI: ${{ secrets.MONGODB_PUBLIC_URI }}
      JWT_SECRET: ${{ secrets.JWT_SECRET }}
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install dependencies
        run: npm install

  unit:
    runs-on: self-hosted
    needs: build
    env:
      PORT: 5001
      MONGODB_ADMIN_URI: ${{ secrets.MONGODB_ADMIN_URI }}
      MONGODB_PUBLIC_URI: ${{ secrets.MONGODB_PUBLIC_URI }}
      JWT_SECRET: ${{ secrets.JWT_SECRET }}
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install dependencies
        run: npm install
      - name: Start backend server
        run: npm start &
      - name: Run unit tests
        run: npm test tests/unit/

  integration:
    runs-on: self-hosted
    needs: unit
    env:
      PORT: 5001
      MONGODB_ADMIN_URI: ${{ secrets.MONGODB_ADMIN_URI }}
      MONGODB_PUBLIC_URI: ${{ secrets.MONGODB_PUBLIC_URI }}
      JWT_SECRET: ${{ secrets.JWT_SECRET }}
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install dependencies
        run: npm install
      - name: Start backend server
        run: npm start &
      - name: Run integration tests
        run: npm test tests/integration/

  security:
    runs-on: self-hosted
    needs: integration
    env:
      PORT: 5001
      MONGODB_ADMIN_URI: ${{ secrets.MONGODB_ADMIN_URI }}
      MONGODB_PUBLIC_URI: ${{ secrets.MONGODB_PUBLIC_URI }}
      JWT_SECRET: ${{ secrets.JWT_SECRET }}
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install dependencies
        run: npm install
      - name: Start backend server
        run: npm start &
      - name: Run security tests
        run: npm test tests/security/